projects:
  reactamplified:
    schemaPath: amplify\backend\api\reactamplified\schema.graphql
    includes:
      - src/graphql/**/*.js
      - aws_directives.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
